# Site settings
title: Isaque Profeta's Blog
email:
description: >-
  Some IT stories, thougts and guides.
baseurl: "/"
url: "http://isaqueprofeta.github.io"
twitter_username: isaqueprofeta
github_username: isaqueprofeta

# Build settings
markdown: kramdown
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
